version: '3.3'

services:

  examanager-server:
    build:
      context: ./examanager-server # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
        - 8080:8080
    env_file: .env
    environment:
        - USER=$USER
        - PASSWORD=$PASSWORD
        - DATABASE=$DATABASE

  client:
    build:
      context: ./examanager-client
      dockerfile: Dockerfile
    image: examanager-client
    stdin_open: true
    container_name: examanager-react-client
    depends_on:
      - examanager-server
    ports:
      - "3000:3000"

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
