version: '3.3'

services:
  examanager-server:
    build:
      context: ./examanager-server # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
        - 8080:8080
    depends_on:
        - mongo
    env_file: .env
    environment:
        - MONGO_HOSTNAME=$MONGO_HOSTNAME
        - MONGO_PORT=$MONGO_PORT
        - MONGO_DB=$MONGO_DB
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    container_name: examanager-mongodb
    ports:
      - "27017:27017"

  client:
    build:
      context: ./examanager-client
      dockerfile: Dockerfile
    image: examanager-client
    stdin_open: true
    container_name: examanager-react-client
    command: yarn start
    volumes:
      - ./examanager-client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - examanager-server
    ports:
      - "3000:3000"

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
